pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/vyadavP7/Salary-API.git'
            }
        }
    }
}
