pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the repository
                git branch: 'main', url: 'https://github.com/vyadavP7/Salary-API.git'
            }
        }
        stage('Package Artifacts') {
            steps {
                sh 'mvn clean package -DskipTests=true'
            }
        }
        stage('Owasp DP-Check') {
            steps {
                // Run Dependency-Check with additional arguments and format HTML
                dependencyCheck additionalArguments: '--scan target/ --format HTML', odcInstallation: 'DP-check',
                                dependencyCheckPublisherPattern: '**/dependency-check-report.html'
            }
        }
    }
}
