pipeline {
    agent any

    stages {
        stage('Code Checkout') {
            steps {
                git branch: 'main', credentialsId: 'Attendance-creds', url: 'https://github.com/OT-MICROSERVICES/attendance-api.git'
            }
        }
        
        stage('Install dependencies') {
            steps {
                // Install dependencies using pip
                sh 'pip install -r requirements.txt'
            }
        }
        
        stage('Static code analysis') {
            steps {
                // Run pylint for static code analysis
                sh 'find . -name \\*.py | xargs pylint | tee pylint.log'
            }
        }
    }
    
    post {
        always {
            // Archive pylint reports
            archiveArtifacts artifacts: '**/pylint.log', allowEmptyArchive: true
        }
    }
}
