pipeline {
    agent any

    environment {
        // Define a list of Python packages to install
        PYTHON_PACKAGES = 'pylint==2.12.2'
    }
            

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'Attendance-creds', url: 'https://github.com/OT-MICROSERVICES/attendance-api.git'
            }
        }


            
        stage('Install dependencies') {
            steps {
                // Install the specified Python packages
                sh "pip install ${env.PYTHON_PACKAGES}"
            }
        }

        stage('Static code analysis') {
            steps {
                // Run pylint on your Python code
                sh 'pylint your_python_script.py'
            }
            post {
                always {
                    // Archive pylint reports
                    archiveArtifacts artifacts: 'pylint-report/*', onlyIfSuccessful: true
                }
            }
        }

        stage('Publish results') {
            steps {
                // Publish pylint reports
                // This step assumes that you have a Jenkins plugin like 'HTML Publisher Plugin' installed
                publishHTML(target: [
                    allowMissing: false,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'pylint-report',
                    reportFiles: 'index.html',
                    reportName: 'Pylint Report'
                ])
            }
        }
    }

    post {
        always {
            // Clean up workspace
            cleanWs()
        }
    }
}
