node {
    stage('Checkout GIT') {
        checkout scm: [
            $class: 'GitSCM',
            branches: [[name: '*/main']],
            userRemoteConfigs: [[url: 'https://github.com/OT-MICROSERVICES/salary-api.git']]
        ]
        sh 'ls $WORKSPACE/'
    }
    
    stage('Starting Code Compilation') {
        echo 'Starting Java Code Compilation..........'
        sh 'mvn clean compile'
    }
}


