pipeline {
    agent any
    tools {
      maven 'mvn'
    }
    stages {
        stage('Checkout GIT') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/OT-MICROSERVICES/salary-api.git']])
            }
        }
        
        stage('Checkout GIT') {
            steps {
                sh 'echo "Starting Java Code Compilation.........."'}
        }
        
        stage('mvn compile') {
            steps {
            sh 'mvn clean compile'
            }
        }
    }
}

